repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
  hooks:
  - id: check-ast
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: debug-statements
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: requirements-txt-fixer
  - id: trailing-whitespace
- repo: https://github.com/myint/autoflake
  rev: v2.0.1
  hooks:
  - id: autoflake
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    args: ["--profile", "black", --line-length=79]
- repo: https://github.com/ambv/black
  rev: '23.1.0'
  hooks:
  - id: black
    args: [--line-length=79]
    language_version: python3.10
- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
- repo: https://github.com/codespell-project/codespell
  rev: v2.2.2
  hooks:
  - id: codespell
    name: codespell
    description: Checks for common misspellings in text files.
    args: ['--skip','Dockerfile,*.md,*.pdf,*.json,*.lock,*.drawio', "-L", "keypairs,keypair,zar,acn,tha"]
    language: python
    types: [text]
- repo: https://github.com/PyCQA/bandit
  rev: '1.7.4'
  hooks:
  - id: bandit
    name: bandit
    description: 'Bandit is a tool for finding common security issues in Python code'
    args: ['-c', 'bandit.yml']
    entry: bandit
    language: python
    language_version: python3
    types: [python]
